"""§6.6 (Issue #6, PR-9.5) — rendered DOM sidebar width matches the spec.

Switches between representative tabs in Playwright and asserts the
``#sidebar-col`` element's ``offsetWidth`` falls within ±2 % of the
expected pixel width derived from
``frontend.ui_standards.TAB_SIDEBAR_WIDTH``.

This is the "spec stays honest" test from §6.6: DOM disagrees with the
constants module ⇒ test fails ⇒ either fix the code or update the
constant + the doc + this test in one PR.

Sample size kept small (3 tabs covering wide + narrow) to stay inside
PR-3's Q3 5-min UI lane budget. PR-10's full coverage will sweep all
15 tabs as part of the broader §5.6 inventory.
"""

from __future__ import annotations

import pytest

from frontend import ui_standards

# Representative tabs — one wide, two narrow (covering both major sidebar
# widths used by the 15-tab matrix). The test_param_apply_roundtrip flow
# already exercises ``metrics``, so we lead with it; ``snapshots`` and
# ``about`` cover the narrow class.
_REPRESENTATIVE_TABS = ["metrics", "snapshots", "about"]

# tab_id → visible label (dbc.Tabs renders tabs by their ``label`` text;
# there's no machine-readable selector that maps back to the ``tab_id``
# in dbc 2.x, so we encode the (small) sample directly. PR-10 will
# extend this if it sweeps all 15 tabs.)
_TAB_LABELS: dict[str, str] = {
    "metrics": "Training Metrics",
    "snapshots": "Snapshots",
    "about": "About",
}


@pytest.mark.ui
@pytest.mark.parametrize("tab", _REPRESENTATIVE_TABS)
def test_sidebar_width_matches_ui_standards(dashboard_page, tab: str) -> None:
    """Switch to ``tab`` and assert the sidebar's pixel width matches
    ``TAB_SIDEBAR_WIDTH[tab] / GRID_COLUMNS × parent-row width``."""
    # Navigate to the tab via Dash's tab API. dbc.Tabs renders each tab's
    # clickable header as an ``<a>`` with the tab id appended to its href
    # ("#metrics", "#snapshots", …); the bootstrap event handler then
    # toggles ``aria-selected`` and fires Dash's active_tab change.
    # dbc.Tabs (Dash 3 / dash-bootstrap-components 2.x) renders tab
    # headers without machine-readable tab_id attributes — every header
    # gets the same react-aria autogenerated id and ``href="#"``. The
    # only stable handle is the visible label. Maintain a tab_id→label
    # map; if a new tab gets added or a label changes, this test fails
    # loudly and the map needs updating in lockstep.
    label = _TAB_LABELS[tab]
    header = dashboard_page.locator(f"#visualization-tabs >> a:has-text('{label}')").first
    assert header.count() > 0, f"could not locate tab header with label {label!r} (tab_id={tab!r})"

    # Capture the sidebar width BEFORE the click so we can poll for change
    # — a fixed sleep races the resize_sidebar_for_tab server callback
    # (causing intermittent failures in suite runs).
    width_before = dashboard_page.evaluate("() => document.getElementById('sidebar-col').offsetWidth")
    header.click()

    expected_fraction_pct = ui_standards.TAB_SIDEBAR_WIDTH.get(tab, ui_standards.WIDE_SIDEBAR) / ui_standards.GRID_COLUMNS
    # Poll until the width matches the expected band OR exceeds a generous
    # timeout; 4 s covers the round-trip even on a slow CI runner.
    dashboard_page.wait_for_function(
        f"""(prev) => {{
            const sidebar = document.getElementById('sidebar-col');
            const row = sidebar.parentElement;
            if (!row || !row.offsetWidth) return false;
            const target = row.offsetWidth * {expected_fraction_pct:.6f};
            const tolerance = Math.max(row.offsetWidth * 0.02, 5);
            return Math.abs(sidebar.offsetWidth - target) <= tolerance;
        }}""",
        arg=width_before,
        timeout=4_000,
    )

    measurements = dashboard_page.evaluate("""() => {
            const sidebar = document.getElementById('sidebar-col');
            if (!sidebar) return null;
            const row = sidebar.parentElement;
            return {sidebar: sidebar.offsetWidth, row: row ? row.offsetWidth : null};
        }""")
    assert measurements is not None, "could not locate #sidebar-col in the rendered DOM"
    assert measurements["row"], f"row container has zero width: {measurements!r}"

    expected_fraction = ui_standards.TAB_SIDEBAR_WIDTH.get(tab, ui_standards.WIDE_SIDEBAR) / ui_standards.GRID_COLUMNS
    expected_px = measurements["row"] * expected_fraction

    # Bootstrap may add small padding/gutters; accept ±2 % of the row width.
    tolerance = max(measurements["row"] * 0.02, 5.0)
    actual = measurements["sidebar"]
    assert abs(actual - expected_px) <= tolerance, f"sidebar width on tab {tab!r}: actual={actual:.1f}px, expected≈{expected_px:.1f}px (±{tolerance:.1f}px); row={measurements['row']:.0f}px, fraction={expected_fraction:.3f}"
