"""§6.6 (Issue #6, PR-9.5 + PR-10 expansion) — rendered DOM sidebar width matches the spec.

Switches between every tab in ``ui_standards.TAB_SIDEBAR_WIDTH`` (15
total) and asserts the ``#sidebar-col`` element's ``offsetWidth`` falls
within ±2 % of the expected pixel width derived from
``TAB_SIDEBAR_WIDTH[tab] / GRID_COLUMNS × parent-row width``.

This is the "spec stays honest" test from §6.6: DOM disagrees with the
constants module ⇒ test fails ⇒ either fix the code or update the
constant + the doc + this test in one PR.

PR-9.5 shipped 3 representative tabs; PR-10 expanded to the full
15-tab matrix per §5.6 inventory. The (tab_id → label) map is parsed
from ``dashboard_manager.py`` at test-collection time so a new tab
added there automatically gets a test entry — no two-place edit.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from frontend import ui_standards

_DASHBOARD_PATH = Path(__file__).resolve().parents[2] / "frontend" / "dashboard_manager.py"


def _parse_tab_labels() -> dict[str, str]:
    """Extract ``{tab_id: label}`` from ``dashboard_manager.py``'s ``dbc.Tab(...)`` blocks.

    Each ``dbc.Tab`` in the layout is constructed with adjacent ``label="X"``
    and ``tab_id="y"`` keyword arguments. We grep the source for those
    pairs rather than introspect the live DashboardManager — keeps the
    test free of Dash-app construction overhead and lets the parametrize
    list be available at collection time.
    """
    text = _DASHBOARD_PATH.read_text()
    pattern = re.compile(r'label="([^"]+)",\s*\n\s*tab_id="([^"]+)"', re.M)
    return {tab_id: label for label, tab_id in pattern.findall(text)}


_TAB_LABELS: dict[str, str] = _parse_tab_labels()
# Tabs we expect to test: every entry in TAB_SIDEBAR_WIDTH that we have a
# label for. (If TAB_SIDEBAR_WIDTH adds a tab whose dbc.Tab definition
# isn't in dashboard_manager yet, the assertion below fails fast.)
_ALL_TABS = sorted(ui_standards.TAB_SIDEBAR_WIDTH.keys())


@pytest.mark.regression
def test_every_known_tab_has_a_label_mapping() -> None:
    """Fail loudly if ``ui_standards.TAB_SIDEBAR_WIDTH`` adds a tab whose
    ``dbc.Tab`` definition is missing from ``dashboard_manager.py`` — the
    parametrized test below would otherwise KeyError at collection time."""
    missing = [tab for tab in _ALL_TABS if tab not in _TAB_LABELS]
    assert not missing, f"these TAB_SIDEBAR_WIDTH entries have no dbc.Tab definition in dashboard_manager.py: {missing}"


@pytest.mark.ui
@pytest.mark.parametrize("tab", _ALL_TABS)
def test_sidebar_width_matches_ui_standards(dashboard_page, tab: str) -> None:
    """Switch to ``tab`` and assert the sidebar's pixel width matches
    ``TAB_SIDEBAR_WIDTH[tab] / GRID_COLUMNS × parent-row width``."""
    # dbc.Tabs (Dash 3 / dash-bootstrap-components 2.x) renders tab
    # headers without machine-readable tab_id attributes — every header
    # gets the same react-aria autogenerated id and ``href="#"``. The
    # only stable handle is the visible label.
    label = _TAB_LABELS[tab]
    header = dashboard_page.locator(f"#visualization-tabs >> a:has-text('{label}')").first
    assert header.count() > 0, f"could not locate tab header with label {label!r} (tab_id={tab!r})"

    # Capture the sidebar width BEFORE the click so we can poll for change
    # — a fixed sleep races the resize_sidebar_for_tab server callback
    # (causing intermittent failures in suite runs).
    width_before = dashboard_page.evaluate("() => document.getElementById('sidebar-col').offsetWidth")
    header.click()

    expected_fraction_pct = ui_standards.TAB_SIDEBAR_WIDTH.get(tab, ui_standards.WIDE_SIDEBAR) / ui_standards.GRID_COLUMNS
    # Poll until the width matches the expected band OR exceeds a generous
    # timeout; 4 s covers the round-trip even on a slow CI runner.
    dashboard_page.wait_for_function(
        f"""(prev) => {{
            const sidebar = document.getElementById('sidebar-col');
            const row = sidebar.parentElement;
            if (!row || !row.offsetWidth) return false;
            const target = row.offsetWidth * {expected_fraction_pct:.6f};
            const tolerance = Math.max(row.offsetWidth * 0.02, 5);
            return Math.abs(sidebar.offsetWidth - target) <= tolerance;
        }}""",
        arg=width_before,
        timeout=4_000,
    )

    measurements = dashboard_page.evaluate("""() => {
            const sidebar = document.getElementById('sidebar-col');
            if (!sidebar) return null;
            const row = sidebar.parentElement;
            return {sidebar: sidebar.offsetWidth, row: row ? row.offsetWidth : null};
        }""")
    assert measurements is not None, "could not locate #sidebar-col in the rendered DOM"
    assert measurements["row"], f"row container has zero width: {measurements!r}"

    expected_fraction = ui_standards.TAB_SIDEBAR_WIDTH.get(tab, ui_standards.WIDE_SIDEBAR) / ui_standards.GRID_COLUMNS
    expected_px = measurements["row"] * expected_fraction

    # Bootstrap may add small padding/gutters; accept ±2 % of the row width.
    tolerance = max(measurements["row"] * 0.02, 5.0)
    actual = measurements["sidebar"]
    assert abs(actual - expected_px) <= tolerance, f"sidebar width on tab {tab!r}: actual={actual:.1f}px, expected≈{expected_px:.1f}px (±{tolerance:.1f}px); row={measurements['row']:.0f}px, fraction={expected_fraction:.3f}"
