---
#####################################################################################################################################################################################################
# Project:       Juniper
# Sub-Project:   JuniperCanopy
# Application:   juniper_canopy
# Purpose:       Monitoring and Diagnostic Frontend for Cascade Correlation Neural Network
#
# Author:        Paul Calnon
# Version:       0.1.4 (0.7.3)
# File Name:     .markdownlint.yaml
# File Path:     <Project>/<Sub-Project>/<Application>/conf/
#
# Date:          2025-12-09
# Last Modified: 2026-01-12
#
# License:       MIT License
# Copyright:     Copyright (c) 2024,2025,2026 Paul Calnon
#
# Description:
#     Markdown Linter Config file
#
#####################################################################################################################################################################################################
# Notes:
#     MD029/ol-prefix: Ordered list item prefix [Expected: 1; Actual: 7; Style: 1/2/3]
#     MD013/line-length: Line length [Expected: 80; Actual: 89]
#     MD046/code-block-style: Code block style [Expected: fenced; Actual: indented]
#
########################################################################################################)#############################################################################################
# References:
#
#     [MD001](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md001.md) heading-increment                - Heading levels should only increment by one level at a time
#     [MD003](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md003.md) heading-style                    - Heading style
#     [MD004](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md004.md) ul-style                         - Unordered list style
#     [MD005](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md005.md) list-indent                      - Inconsistent indentation for list items at the same level
#     [MD007](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md007.md) ul-indent                        - Unordered list indentation
#     [MD009](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md009.md) no-trailing-spaces               - Trailing spaces
#     [MD010](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md010.md) no-hard-tabs                     - Hard tabs
#     [MD011](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md011.md) no-reversed-links                - Reversed link syntax
#     [MD012](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md012.md) no-multiple-blanks               - Multiple consecutive blank lines
#     [MD013](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md013.md) line-length                      - Line length
#     [MD014](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md014.md) commands-show-output             - Dollar signs used before commands without showing output
#     [MD018](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md018.md) no-missing-space-atx             - No space after hash on atx style heading
#     [MD019](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md019.md) no-multiple-space-atx            - Multiple spaces after hash on atx style heading
#     [MD020](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md020.md) no-missing-space-closed-atx      - No space inside hashes on closed atx style heading
#     [MD021](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md021.md) no-multiple-space-closed-atx     - Multiple spaces inside hashes on closed atx style heading
#     [MD022](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md022.md) blanks-around-headings           - Headings should be surrounded by blank lines
#     [MD023](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md023.md) heading-start-left               - Headings must start at the beginning of the line
#     [MD024](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md024.md) no-duplicate-heading             - Multiple headings with the same content
#     [MD025](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md025.md) single-title/single-h1           - Multiple top level headings in the same document
#     [MD026](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md026.md) no-trailing-punctuation          - Trailing punctuation in heading
#     [MD027](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md027.md) no-multiple-space-blockquote     - Multiple spaces after blockquote symbol
#     [MD028](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md028.md) no-blanks-blockquote             - Blank line inside blockquote
#     [MD029](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md029.md) ol-prefix                        - Ordered list item prefix
#     [MD030](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md030.md) list-marker-space                - Spaces after list markers
#     [MD031](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md031.md) blanks-around-fences             - Fenced code blocks should be surrounded by blank lines
#     [MD032](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md032.md) blanks-around-lists              - Lists should be surrounded by blank lines
#     [MD033](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md033.md) no-inline-html                   - Inline HTML
#     [MD034](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md034.md) no-bare-urls                     - Bare URL used
#     [MD035](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md035.md) hr-style                         - Horizontal rule style
#     [MD036](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md036.md) no-emphasis-as-heading           - Emphasis used instead of a heading
#     [MD037](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md037.md) no-space-in-emphasis             - Spaces inside emphasis markers
#     [MD038](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md038.md) no-space-in-code                 - Spaces inside code span elements
#     [MD039](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md039.md) no-space-in-links                - Spaces inside link text
#     [MD040](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md040.md) fenced-code-language             - Fenced code blocks should have a language specified
#     [MD041](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md041.md) first-line-heading/first-line-h1 - First line in file should be a top level heading
#     [MD042](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md042.md) no-empty-links                   - No empty links
#     [MD043](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md043.md) required-headings                - Required heading structure
#     [MD044](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md044.md) proper-names                     - Proper names should have the correct capitalization
#     [MD045](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md045.md) no-alt-text                      - Images should have alternate text (alt text)
#     [MD046](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md046.md) code-block-style                 - Code block style
#     [MD047](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md047.md) single-trailing-newline          - Files should end with a single newline character
#     [MD048](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md048.md) code-fence-style                 - Code fence style
#     [MD049](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md049.md) emphasis-style                   - Emphasis style should be consistent
#     [MD050](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md050.md) strong-style                     - Strong style should be consistent
#     [MD051](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md051.md) link-fragments                   - Link fragments should be valid
#     [MD052](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md052.md) reference-links-images           - Reference links and images should use a label that is defined
#     [MD053](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md053.md) link-image-reference-definitions - Link and image reference definitions should be needed
#     [MD054](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md054.md) link-image-style                 - Link and image style
#     [MD055](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md055.md) table-pipe-style                 - Table pipe style
#     [MD056](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md056.md) table-column-count               - Table column count
#     [MD058](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md058.md) blanks-around-tables             - Tables should be surrounded by blank lines
#     [MD059](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md059.md) descriptive-link-text            - Link text should be descriptive
#
#####################################################################################################################################################################################################
# TODO :
#
#####################################################################################################################################################################################################
# COMPLETED:
#
#####################################################################################################################################################################################################

# Markdownlint rule configuration for markdownlint-cli
default: true

# MD029/ol-prefix: disable ordered list item prefix rule
MD029: false

# MD013/line-length: increase allowed line length
MD013:
  line_length: 512

# MD046/code-block-style: use a consistent code block style
MD046:
  style: consistent

# MD036/no-emphasis-as-heading: allow emphasis used instead of a heading
MD036: false
